import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';
import tailwindcss from '@tailwindcss/vite';
import glob from 'fast-glob';

export default defineConfig({
    plugins: [
        laravel({
            input:
                [
                    'resources/css/app.css',
                    'resources/js/app.js',


                    'resources/css/About_Styles.css',
                    'resources/css/Admin_Styles.css',
                    'resources/css/CompFund_Styles.css',
                    'resources/css/Courses_Styles.css',
                    'resources/css/Dashboard_Styles.css',
                    'resources/css/DiffCall_Styles.css',
                    'resources/css/DigiLogic_Styles.css',
                    'resources/css/Landing_Styles.css',
                    'resources/css/Login_Signup_Styles.css',
                    'resources/css/Login_Styles.css',
                    'resources/css/Module_Show_Toast_Styles.css',
                    'resources/css/Profile_Styles.css',
                    'resources/css/ProgFund_Styles.css',
                    'resources/css/Register_Styles.css',
                    'resources/css/Community_Styles.css',
                    'resources/css/Quiz_Result_Styles.css',

                    'resources/css/modules/compfund/mod1/practice1.css',
                    'resources/css/modules/compfund/mod1/quiz1.css',
                    'resources/css/modules/compfund/mod1/review1.css',
                    'resources/css/modules/compfund/mod2/practice2.css',
                    'resources/css/modules/compfund/mod2/quiz2.css',
                    'resources/css/modules/compfund/mod2/review2.css',
                    'resources/css/modules/compfund/mod3/practice3.css',
                    'resources/css/modules/compfund/mod3/quiz3.css',
                    'resources/css/modules/compfund/mod3/review3.css',
                    'resources/css/modules/compfund/mod4/practice4.css',
                    'resources/css/modules/compfund/mod4/quiz4.css',
                    'resources/css/modules/compfund/mod4/review4.css',
                    'resources/css/modules/compfund/mod5/practice5.css',
                    'resources/css/modules/compfund/mod5/quiz5.css',
                    'resources/css/modules/compfund/mod5/review5.css',

                    'resources/css/modules/diffcalc/mod1/practice1.css',
                    'resources/css/modules/diffcalc/mod1/quiz1.css',
                    'resources/css/modules/diffcalc/mod1/review1.css',
                    'resources/css/modules/diffcalc/mod2/practice2.css',
                    'resources/css/modules/diffcalc/mod2/quiz2.css',
                    'resources/css/modules/diffcalc/mod2/review2.css',
                    'resources/css/modules/diffcalc/mod3/practice3.css',
                    'resources/css/modules/diffcalc/mod3/quiz3.css',
                    'resources/css/modules/diffcalc/mod3/review3.css',
                    'resources/css/modules/diffcalc/mod4/practice4.css',
                    'resources/css/modules/diffcalc/mod4/quiz4.css',
                    'resources/css/modules/diffcalc/mod4/review4.css',
                    'resources/css/modules/diffcalc/mod5/practice5.css',
                    'resources/css/modules/diffcalc/mod5/quiz5.css',
                    'resources/css/modules/diffcalc/mod5/review5.css',
                    'resources/css/modules/diffcalc/mod6/practice6.css',
                    'resources/css/modules/diffcalc/mod6/quiz6.css',
                    'resources/css/modules/diffcalc/mod6/review6.css',
                    'resources/css/modules/diffcalc/mod7/practice7.css',
                    'resources/css/modules/diffcalc/mod7/quiz7.css',
                    'resources/css/modules/diffcalc/mod7/review7.css',

                    'resources/css/modules/digilogic/mod1/practice1.css',
                    'resources/css/modules/digilogic/mod1/quiz1.css',
                    'resources/css/modules/digilogic/mod1/review1.css',
                    'resources/css/modules/digilogic/mod2/practice2.css',
                    'resources/css/modules/digilogic/mod2/quiz2.css',
                    'resources/css/modules/digilogic/mod2/review2.css',
                    'resources/css/modules/digilogic/mod3/practice3.css',
                    'resources/css/modules/digilogic/mod3/quiz3.css',
                    'resources/css/modules/digilogic/mod3/review3.css',
                    'resources/css/modules/digilogic/mod4/practice4.css',
                    'resources/css/modules/digilogic/mod4/quiz4.css',
                    'resources/css/modules/digilogic/mod4/review4.css',
                    'resources/css/modules/digilogic/mod5/practice5.css',
                    'resources/css/modules/digilogic/mod5/quiz5.css',
                    'resources/css/modules/digilogic/mod5/review5.css',
                    'resources/css/modules/digilogic/mod6/practice6.css',
                    'resources/css/modules/digilogic/mod6/quiz6.css',
                    'resources/css/modules/digilogic/mod6/review6.css',
                    'resources/css/modules/digilogic/mod7/practice7.css',
                    'resources/css/modules/digilogic/mod7/quiz7.css',
                    'resources/css/modules/digilogic/mod7/review7.css',

                    'resources/css/modules/progfund/mod1/practice1.css',
                    'resources/css/modules/progfund/mod1/quiz1.css',
                    'resources/css/modules/progfund/mod1/review1.css',
                    'resources/css/modules/progfund/mod2/practice2.css',
                    'resources/css/modules/progfund/mod2/quiz2.css',
                    'resources/css/modules/progfund/mod2/review2.css',
                    'resources/css/modules/progfund/mod3/practice3.css',
                    'resources/css/modules/progfund/mod3/quiz3.css',
                    'resources/css/modules/progfund/mod3/review3.css',
                    'resources/css/modules/progfund/mod4/practice4.css',
                    'resources/css/modules/progfund/mod4/quiz4.css',
                    'resources/css/modules/progfund/mod4/review4.css',
                    'resources/css/modules/progfund/mod5/practice5.css',
                    'resources/css/modules/progfund/mod5/quiz5.css',
                    'resources/css/modules/progfund/mod5/review5.css',

                    ...glob.sync('resources/css/modules/**/*.css'),

                    'resources/js/Admin_Scripts.js',
                    'resources/js/CompFund_Scripts.js',
                    'resources/js/Courses_Scripts.js',
                    'resources/js/Dashboard_Scripts.js',
                    'resources/js/DiffCall_Scripts.js',
                    'resources/js/DigiLogic_Scripts.js',
                    'resources/js/Landing_Scripts.js',
                    'resources/js/Login_Scripts.js',
                    'resources/js/Login_Signup_Scripts.js',
                    'resources/js/Profile_Scripts.js',
                    'resources/js/ProgFund_Scripts.js',
                    'resources/js/Register_Scripts.js',
                    'resources/js/Community_Scripts.js',
                    'resources/js/About_Scripts.js',
                    'resources/js/Quiz_Result_Scripts.js'


                ],
            refresh: true,
        }),
        tailwindcss(),
    ],
});
